{% set name = "Flask-Dance" %}
{% set version = "7.0.0" %}
{% set sha256 = "a37dec5c3a21f13966178285d5c10691cd72203dcef8a01db802fef6287e716d" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }} 

build:
  number: {{ build_number }}
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3.2, <4
  run:
    - python >=3.7
    - requests >=2.0
    - oauthlib >=3.2
    - requests-oauthlib >=1.0.0
    - Flask >=2.0.3
    - urlobject
    - Werkzeug

test:
  imports:
    - flask_dance
    - flask_dance.consumer
    - flask_dance.consumer.storage
    - flask_dance.contrib

about:
  home: https://pypi.org/project/Flask-Dance/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Doing the OAuth dance with style using Flask, requests, and oauthlib.'

  doc_url: http://flask-dance.readthedocs.io/
  dev_url: https://github.com/singingwolfboy/flask-dance

extra:
  recipe-maintainers:
    - rmarow
    - ericcina
